### ISSUE TITLE
Issue with running snakemake 

### ISSUE THREAD

**Issue by szhang99-bu** [theislab/scib-pipeline#8] opened 2021-07-21 02:43 UTC
I am currently all set up according to the instruction, then should we run snakemake in the base environment?
If so, when I am running the pipeline for either my own data or the test data, a syntax error occurs:

SyntaxError:
Input and output files have to be specified as strings or list of strings/
        xxxxxx/xxxxx/xxxxxx/ scib-pipeline/Snakefile, line 10, in module
        xxxxxx/xxxxx/xxxxxx/ scib-pipeline/scripts/preprocessing/Snakefile, line 23, in module

**Comment by LuckyMD** [comment] 2021-07-21 08:48
I'll close this as a duplicate of #9 which I transferred from scIB.

**Closed by LuckyMD** 2021-07-21 08:48 UTC
